# Generated by Django 5.2.8 on 2025-11-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_flavor_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='falvor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.flavor'),
        ),
    ]
