# Generated by Django 5.2.8 on 2025-11-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartitem_falvor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='falvor',
            new_name='flavor',
        ),
    ]
