# Generated by Django 5.2.8 on 2025-11-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_flavor_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='price',
        ),
        migrations.AddField(
            model_name='amount',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
