# Generated by Django 5.2.8 on 2025-11-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_flavor_price_amount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='store.product'),
        ),
    ]
